project:
  type: book

book:
  title: "Curso de Programação Estatística"
  author: "Andressa Cerqueira, Rafael Izbicki, Thiago Rodrigo Ramos"
  date: today
  cover-image: cover.png
  chapters:
    - index.qmd
    - 1_intro.qmd
    - 2_pseudorandom.qmd
    - 3_discrete_inversion.qmd
    - 4_continuous_inversion.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/thiagorr162/prog-estat
        aria-label: GitHub

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 2
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2

editor: source

execute:
  message: false
  warning: false

